include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    # Treat these as errors, not warnings
    invalid_annotation_target: ignore # drift generates these

linter:
  rules:
    avoid_print: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_rethrow_when_possible: true
